name: VoxelGamesLib
version: ${version.number}
main: com.voxelgameslib.voxelgameslib.VoxelGamesLib
authors: [VoxelGamesLib]
depend: [VoxelGamesLib-Dependencies]
website: https://github.com/VoxelGamesLib/VoxelGamesLibv2