name: VoxelGamesLib
version: @version@
main: com.voxelgameslib.voxelgameslib.VoxelGamesLib
authors: [VoxelGamesLib]
depend: [VoxelGamesLib-Dependencies]
website: https://github.com/VoxelGamesLib/VoxelGamesLibv2